### ISSUE TITLE
Amazon ECSの適当な参考資料を探す・選ぶ

### ISSUE THREAD

**Issue by nobishino** [evt-mob-docker/mob_docker#32]

**Comment by TaroTakanashi** [comment]
https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/Welcome.html

**Comment by nobishino** [comment]
上のページ内の[チュートリアル一覧](https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/ECS_AWSCLI_Fargate.html)

**Comment by nobishino** [comment]
- [良さそうな記事](https://qiita.com/uzresk/items/6acc90e80b0a79b961ce)
- 上記の記事で引用されている[BlackBelt](http://www.slideshare.net/AmazonWebServicesJapan/aws-black-belt-online-seminar-2016-amazon-ec2-container-service)
