### ISSUE TITLE
リポジトリをprivateにする(要議論)

### ISSUE THREAD

**Issue by nobishino** [evt-mob-docker/mob_docker#5]
* issueに気兼ねなくquestionとか書いていくにはprivateの方が良い
* 人数的にも大体関心がありそうな人にはリーチできたのでpublicにして宣伝する必要も少ない
* なのでprivateにしてはどうか？

**Comment by TaroTakanashi** [comment]
プライベートにすると、Zen-hubが無料で使えなくなるので当分はパブリックのままで行きます。
