### ISSUE TITLE
Laravel Hello Worldアプリをコンテナ化する

### ISSUE THREAD

**Issue by nobishino** [evt-mob-docker/mob_docker#9]
作ったLaravelのHello Worldアプリをdocker containerにする。

そもそもdocker containerにするとはどういうことかを明らかにすることもスコープに含まれる。

**Comment by nobishino** [comment]
イメージを具体化した：

* LaravelのソースコードとDockerfileをgit repositoryに置く
* そのDockerfileを使ってimageをビルドし、コンテナを起動すると、同梱のソースコードがコンテナにマウントされて、Hello worldアプリが実行できる
* dockerさえインストールしていれば、Hello worldアプリが実行できる状態になる

**Comment by TaroTakanashi** [comment]
composer pharをaliasする
https://askubuntu.com/questions/116960/global-installation-of-composer-manual
